#!/usr/bin/env python3

#download speed test
#valid rows: Server ID,Sponsor,Server Name,Timestamp,Distance,Ping,Download,Upload

#import cgitb ; cgitb.enable()
#import time
import socket
import csv

with open('results.csv') as csvfile:
    reader = csv.DictReader(csvfile)
    for row in reader:
        download = row['Download']

sock = socket.socket()
sock.connect( ("localhost", 2003) )
sock.send("test".encode())
sock.close()


sock = socket.socket()
sock.connect( ("localhost", 2003) )
sock.send(str(download).encode())
sock.close()

sock.send("ad.download " + str(download) + " \n")
#sock.send("ad.download " + str(download) + " " + str(time.time()) + " \n")
#sock.send("ad.upload " + str(upload) + " " + str(time.time()) + " \n")
#sock.send("ad.latency " + str(latency) + " " + str(time.time()) + " \n")
#sock.send("ad.srvid " + str(srvid) + " " + str(time.time()) + " \n")

sock.close()


